pipelines:
  default:
    - parallel:
        - step:
            name: Test latest Node.js version
            image: 'node:latest'
            caches:
              - node
            script:
              - npm ci --unsafe-perm
              - 'npm run manager:build'
              - npm test
        - step:
            name: Test LTS 14 Node.js version
            image: 'node:14'
            caches:
              - node
            script:
              - npm ci --unsafe-perm
              - 'npm run manager:build'
              - npm test
        - step:
            name: Test LTS 12 Node.js version
            image: 'node:12'
            caches:
              - node
            script:
              - npm ci --unsafe-perm
              - 'npm run manager:build'
              - npm test
        - step:
            name: Test LTS 10 Node.js version
            image: 'node:10'
            caches:
              - node
            script:
              - npm ci --unsafe-perm
              - 'npm run manager:build'
              - npm test
