extends: '@absolunet/core'


# Environments
env:
  browser: true


# Rules
rules:

  # Strict Mode
  strict: [error, function]


  # IE11 incompatibility
  require-unicode-regexp: [off]


  # ðŸ¦„ Unicorn
  unicorn/no-document-cookie: [error]
  unicorn/prefer-add-event-listener: [error]
  unicorn/prefer-dom-node-append: [error]
  unicorn/prefer-dom-node-dataset: [error]
  unicorn/prefer-dom-node-remove: [error]
  unicorn/prefer-dom-node-text-content: [error]
  unicorn/prefer-keyboard-event-key: [error]
  unicorn/prefer-modern-dom-apis: [error]
  unicorn/prefer-query-selector: [error]
  unicorn/require-post-message-target-origin: [error]
