extends: '@absolunet/core'


# Environments
env:
  node: true


# Plugins
plugins:
  - node


# Rules
rules:

  # Strict Mode
  strict: [error, global]


  # Node - Possible Errors
  node/handle-callback-err: [error]
  node/no-callback-literal: [off]
  node/no-exports-assign: [error]
  node/no-extraneous-import: [off]
  node/no-extraneous-require: [off]
  node/no-missing-import: [off]
  node/no-missing-require: [off]
  node/no-new-require: [error]
  node/no-path-concat: [error]
  node/no-process-exit: [error]
  node/no-unpublished-bin: [error]
  node/no-unpublished-import: [off]
  node/no-unpublished-require: [error]
  node/no-unsupported-features/es-builtins: [off]  # Transpiler
  node/no-unsupported-features/es-syntax: [off]  # Transpiler
  node/no-unsupported-features/node-builtins: [error]
  node/process-exit-as-throw: [error]
  node/shebang: [error]


  # Node - Best Practices
  node/no-deprecated-api: [error]


  # Node - Stylistic Issues
  node/callback-return: [error]
  node/exports-style: [error, 'module.exports']
  node/file-extension-in-import: [off]
  node/global-require: [error]
  node/no-mixed-requires: [error]
  node/no-process-env: [error]
  node/no-restricted-import: [off]
  node/no-restricted-require: [off]
  node/no-sync: [off]
  node/prefer-global/buffer: [error, never]
  node/prefer-global/console: [error, always]
  node/prefer-global/process: [error, always]
  node/prefer-global/text-decoder: [error, never]
  node/prefer-global/text-encoder: [error, never]
  node/prefer-global/url-search-params: [error, never]
  node/prefer-global/url: [error, never]
  node/prefer-promises/dns: [error]
  node/prefer-promises/fs: [error]


  # ðŸ¦„ Unicorn
  unicorn/no-process-exit: [error]
  unicorn/no-new-buffer: [error]
  unicorn/prefer-module: [off]
  unicorn/prefer-node-protocol: [off]
