extends: '@absolunet/browser'

parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - import
  - flowtype
  - jsx-a11y
  - react

rules:
  unicorn/filename-case: [off]

  # https://github.com/benmosher/eslint-plugin-import/tree/master/docs/rules
  import/first: error
  import/no-amd: error
  import/no-webpack-loader-syntax: error

  # https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
  react/forbid-foreign-prop-types: [warn, { allowInPropTypes: true }]
  react/jsx-no-comment-textnodes: warn
  react/jsx-no-duplicate-props: [warn, { ignoreCase: true }]
  react/jsx-no-target-blank: warn
  react/jsx-no-undef: error
  react/jsx-pascal-case: [
    warn,
    {
      allowAllCaps: true,
      ignore: [],
    },
  ]
  react/jsx-uses-react: warn
  react/jsx-uses-vars: warn
  react/no-danger-with-children: warn
  # Disabled because of undesirable warnings
  # See https://github.com/facebook/create-react-app/issues/5204 for
  # blockers until its re-enabled
  # 'react/no-deprecated': warn,
  react/no-direct-mutation-state: warn
  react/no-is-mounted: warn
  react/react-in-jsx-scope: error
  react/require-render-return: error
  react/style-prop-object: warn

  # https://github.com/evcohen/eslint-plugin-jsx-a11y/tree/master/docs/rules
  jsx-a11y/accessible-emoji: warn
  jsx-a11y/alt-text: warn
  jsx-a11y/anchor-has-content: warn
  jsx-a11y/anchor-is-valid: [
    warn,
    {
      aspects: ['noHref', 'invalidHref'],
    },
  ]
  jsx-a11y/aria-activedescendant-has-tabindex: warn
  jsx-a11y/aria-props: warn
  jsx-a11y/aria-proptypes: warn
  jsx-a11y/aria-role: warn
  jsx-a11y/aria-unsupported-elements: warn
  jsx-a11y/heading-has-content: warn
  jsx-a11y/iframe-has-title: warn
  jsx-a11y/img-redundant-alt: warn
  jsx-a11y/no-access-key: warn
  jsx-a11y/no-distracting-elements: warn
  jsx-a11y/no-redundant-roles: warn
  jsx-a11y/role-has-required-aria-props: warn
  jsx-a11y/role-supports-aria-props: warn
  jsx-a11y/scope: warn

  # https://github.com/gajus/eslint-plugin-flowtype
  flowtype/define-flow-type: warn
  flowtype/require-valid-file-annotation: warn
  flowtype/use-flow-type: warn
